Development complete
juzQrios/css-framework-demo pull request #4
Opened 2019-03-26 12:09 UTC by daashandayo

2019-03-26 12:28 UTC, inhaq requested changes
### Good job 🏅
Everything is good and working as it should. 
Only concern is that, framework is used because of not to write our own custom SCSS. In this project, you're only declaring grid and card for framework and rest of the stuff you're doing in custom SCSS. It would be great if you cut down most of your custom SCSS and put it in framework SCSS. Let me DM on slack if you've any queries. Once fixed, kindly resubmit.

2019-03-26 12:28 UTC, inhaq commented on index.html
> +    </div>
this `div` should be within `footer`

2019-03-27 07:05 UTC, inhaq approved these changes
### 👍🏻for this project
Congrats on completing this project 👏🏻go ahead and submit a project completion form.
I would recommend adding further functionalities to the framework as well. 
Good luck with the next project 🎉

2019-03-27 10:29 UTC, daashandayo commented
@inhaq Our framework now contains paddings, margins, buttons, jumbotron, container, grids

2019-03-27 10:32 UTC, inhaq commented
@daashandayo now instead of writing custom SCSS for your demo site, use your framework classes and remove custom SCSS from the framework.

2019-03-27 10:37 UTC, daashandayo commented
@daashandayo Yeah we removed Custom SCSS and included mixins for margin, padding and jumbotron instead.

2019-03-27 12:53 UTC, merged